swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /asignaturas/{id_asignatura}/info-docente:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Obtener la informacion de docente y asingnatura solicitada
      operationId: NotasController.GetDatosDocenteAsignatura
      parameters:
      - in: path
        name: id_asignatura
        description: Id asignatura
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /asignaturas/{id_asignatura}/modificacion-extemporanea:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Chequear si hay modificacion extemporanea para la asignatura
      operationId: NotasController.GetModificacionExtemporanea
      parameters:
      - in: path
        name: id_asignatura
        description: Id asignatura
        required: true
        type: string
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /asignaturas/{id_asignatura}/periodos/{id_periodo}/porcentajes:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Obtener los porcentajes de la asignatura solicitada
      operationId: NotasController.GetPorcentajesAsignatura
      parameters:
      - in: path
        name: id_asignatura
        description: Id asignatura
        required: true
        type: string
      - in: path
        name: id_periodo
        description: Id periodo
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /asignaturas/porcentajes:
    put:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Modificar los porcentajes de la asignatura solicitada
      operationId: NotasController.PutPorcentajesAsignatura
      parameters:
      - in: body
        name: body
        description: body Modificar registro Asignatura content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: the request contains incorrect syntax
  /docentes/{id_docente}/espacios-academicos:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Listar la carga academica relacionada a determinado docente
      operationId: NotasController.GetEspaciosAcademicosDocente
      parameters:
      - in: path
        name: id_docente
        description: Id docente
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /notas/asignaturas/{id_asignatura}/periodos/{id_periodo}/estudiantes:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Obtener lista de estudiantes con los registros de notas para determinada asignatura
      operationId: NotasController.GetCapturaNotas
      parameters:
      - in: path
        name: id_asignatura
        description: Id asignatura
        required: true
        type: string
      - in: path
        name: id_periodo
        description: Id periodo
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /notas/asignaturas/estudiantes:
    put:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Modificar registro de notas para estudiantes de determinada asignatura
      operationId: NotasController.PutCapturaNotas
      parameters:
      - in: body
        name: body
        description: body Notas Estudiantes
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: the request contains incorrect syntax
  /notas/estudiantes/{id_estudiante}:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Obtener la informacion de estudiante y notas asignaturas
      operationId: NotasController.GetDatosEstudianteNotas
      parameters:
      - in: path
        name: id_estudiante
        description: Id estudiante
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /periodos/{id_periodo}/estados-registros:
    get:
      tags:
      - github.com/udistrital/sga_mid_notas/controllersNotasController
      description: Listar asignaturas docentes  junto estado registro
      operationId: NotasController.GetEstadosRegistros
      parameters:
      - in: path
        name: id_periodo
        description: Id periodo
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
definitions:
  '{}':
    title: '{}'
    type: object
tags:
- name: github.com/udistrital/sga_mid_notas/controllersNotasController
  description: |
    NotasController operations for Notas
